import "./globals.css"; // Ensure your fonts are imported here

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-body"> {/* Default font for body */}
        {children}
      </body>
    </html>
  );
}
